config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  resources :posts, only: [:index, :new, :create, :show]
  resources :comments, only: [:create]

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    @comment.save
    redirect_to @comment.post
  end

  private

  def comment_params
    params.require(:comment).permit(:id, :content, :post_id)
  end
end 

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new    
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  private

  def post_params
    params.require(:post).permit(:id, :title, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
  <div class="text-center"><h1><%= link_to "anony-forum", posts_path %></h1></div>
    <%= yield %>

  </body>
</html>

app/views/posts/index.html.erb
<div class="row">
  <div class="small-10 small-offset-1 columns">
    <%= link_to "Create a new post", new_post_path %>
    <ul>
    <% @posts.each do |p| %>
     <li><%= link_to p.title, post_path(p) %></li>
    <% end %>
    </ul>
  </div>
</div>

app/views/posts/new.html.erb
<br />

<div class="row">
  <div class="small-10 small-offset-1 columns">
    <%= form_for @post, url: {action: :create} do |f| %>
      <%= f.text_field :title %>
      <br />
      <%= f.text_area :description %>

      <%= f.submit %>  
    <% end %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="row">
  <div class="small-10 small-offset-1 columns">
    <h3><%= @post.title %></h3>
  </div>
</div>
<div class="row">
  <div class="small-10 small-offset-1 columns">
    <h4><%= @post.description %></h4>
  </div>
</div>

<div class="row">
  <div class="small-10 small-offset-1 columns">
    <ul>
      <% @post.comments.order(:created_at).each do |cmt| %>
        <li><%= cmt.content %></li>
      <% end %>
    </ul>
  </div>
</div>

<div class="row">
  <div class="small-10 small-offset-1 columns">
    <%= form_for(Comment.new, url: comments_path) do |f| %>
      <%= f.text_field :content %>
      <%= f.hidden_field :post_id, value: @post.id %>
      <%= f.submit %>
    <% end %>
  </div>
</div>